apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jobtracker

commonLabels:
  app.kubernetes.io/part-of: jobtracker

resources:
  - namespace.yaml
  - postgres.yaml
  - redis.yaml
  - kafka.yaml
  - application-service.yaml
  - notification-service.yaml
  - analytics-service.yaml
