apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: jobtracker
type: Opaque
stringData:
  POSTGRES_DB: jobtracker
  POSTGRES_USER: jobtrackeru
  POSTGRES_PASSWORD: jobtracker1
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: jobtracker
spec:
  clusterIP: None
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: jobtracker
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:18-alpine
          envFrom:
            - secretRef:
                name: postgres-credentials
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "jobtrackeru", "-d", "jobtracker"]
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            requests: { cpu: "100m", memory: "256Mi" }
            limits: { cpu: "500m", memory: "512Mi" }
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi
